Add ability to ignore files, add new keywords.
rory/django-template-i18n-lint pull request #26
Opened 2019-03-14 10:23 UTC by Skeen

2021-10-04 04:21 UTC, jayvdb requested changes

2021-10-04 04:21 UTC, jayvdb commented on README.md
> +Fork of original project by Rory McCann, [https://github.com/rory/django-template-i18n-lint](https://github.com/rory/django-template-i18n-lint), description by original author: [Lint tool to find non
these are the same repo.  I think you should remove

2021-10-04 04:21 UTC, jayvdb commented on README.md
> -It can also automatically wrap the strings in `{% trans "" %}` tags, by running it with the `-r` command-line flag.
I think the `-r` mode is worth mentioning on the README.

2021-10-04 04:21 UTC, jayvdb commented on README.md
> +Usefull hints:
one `l` in useful

2022-01-18 11:12 UTC, Skeen commented
I do not utilize this project anymore, and thus I am unfortunately not gonna work to get this merged.

2022-01-18 11:12 UTC, closed without merging